### PR TITLE
add missing payload buttons and map them to corresponding joystick bu…

### PR DESCRIPTION
**Pull request by MblRobotics**
…ttons

### CODE REVIEW

**Comment by offgrid88** [comment]
**payload buttons and joystick buttons works and deliver messages to the MCU  ✅**

**Comment by offgrid88** [comment]
If no bugs are found,this should be the Final PR to release the V.1.0.0

**Comment by ridha-mastouri** [comment]
@offgrid88 can you test it from your side?

**Comment by offgrid88** [comment]
> @offgrid88 can you test it from your side?

I tested and it is working withno problem, I controlled servos with joystick and GUI

**Pull request merged**
